import Head from "next/Head";
import { ReactChild } from "react";
import SideBar from "../Sidebar";
import TopBar from "../Topbar";

type Props = {
  title: string;
  children: ReactChild;
};

export default function Layout({ title, children }: Props) {
  return (
    <div className="bg-gray-300">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <TopBar /> */}
      {/* <SideBar /> */}

      <main className="container mx-auto max-w-xl pt-8 min-h-screen">
        {children}
      </main>
    </div>
  );
}
