export const typesBackground: any = {
  grass: "bg-green-200",
  fire: "bg-red-200",
  water: "bg-blue-200",
  bug: "bg-green-50",
  flying: "bg-gray-400",
  poison: "bg-purple-200",
  electric: "bg-yellow-100",
  ground: "bg-yellow-100",
  normal: "bg-gray-100",
  fairy: "bg-pink-200",
  fighting: "bg-red-300",
  rock: "bg-yellow-100",
  psychic: "bg-pink-200",
  steel: "bg-gray-300",
  ice: "bg-blue-200",
  dragon: "bg-indigo-200",
};

export const typesColor: any = {
  grass: "bg-green-700 text-white",
  fire: "bg-red-500 text-white",
  water: "bg-blue-500 text-white",
  bug: "bg-green-500",
  poison: "bg-purple-500 text-white",
  electric: "bg-yellow-300",
  normal: "bg-gray-300",
  flying: "bg-blue-900 text-white",
  ground: "bg-yellow-700 text-white",
  fairy: "bg-pink-500 text-white",
  fighting: "bg-yellow-800 text-white",
  rock: "bg-yellow-900 text-white",
  psychic: "bg-pink-400 text-white",
  steel: "bg-gray-500 text-white",
  ice: "bg-blue-500 text-white",
  dragon: "bg-indigo-800 text-white",
};
